title: SLK R171 Restaurierungstagebuch
email: rwuestner@mailbox.org
description: >-
  Willkommen im Logbuch meines Mercedes SLK R171 Kompressor.
baseurl: "https://wuestner.github.io/r171/"
url: "https://wuestner.github.io/r171/"
theme: minima
markdown: kramdown
