title: SLK R171 Restaurierungstagebuch
email: rwuestner@mailbox.org
description: >-
  Willkommen im Logbuch meines Mercedes SLK R171 Kompressor.
baseurl: "/r171"
url: "https://wuestner.github.io"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
markdown: kramdown
