title: SLK R171 Restaurierungstagebuch
email: your-email@example.com
description: >-
  Willkommen im Restaurierungstagebuch meines Mercedes SLK R171 Kompressor.
baseurl: ""
url: "https://your-github-username.github.io"
theme: minima
markdown: kramdown
