title: SLK R171 Restaurierungstagebuch
email: rwuestner@mailbox.org
description: >-
  Willkommen im Logbuch meines Mercedes SLK R171 Kompressor.
baseurl: "/r171"
url: "https://wuestner.github.io"
theme: minima
markdown: kramdown
